PIC_FILE = ('jpg', 'jpeg', 'png')
PIC_SIZE = 5_242_880  # размер в байтах, сейчас 5 мб
ONE_MB_SIZE = 1_048_576
ID_LEN_MIN = 6
ID_LEN_MAX = 10
LINK_LEN_MIN = 6
LINK_LEN_MAX = 127
OK_MSG = 'Начало обработки...'
NOT_OK_MSG = 'Что-то сломалось в модулях обработки'
